### ISSUE TITLE
request for the data to reconstruct the results

### ISSUE THREAD

**Issue by copykaty** [tum-pbs/Global-Flow-Transport#1]
Hi, great work! We are trying to reproduce your results in the paper. However, since the data size in the open-source scalarflow dataset is different from the setting in this paper, we cannot re-run your other reconstruct json. Moreover, our result with "mv_globt_small.json" showcases quite strange camera view, could you please share your experiment data for the json files, or provide some references for your data pre-processeing method. Looking forward to your reply. Thanks!

**Comment by eftum** [comment]
Hello,
The spatial resolution of ScalarFlow is indeed different from the one used here, but the script should handle this automatically. We do not apply any additional pre-processing.
Where did you get the ScalarFlow dataset from and what data size does it have?
What error do you get if you try to run the reconstruction with it?
I understand that the "mv_globt_small.json" version works for you?

If the results you are refering to are the renderings done peridically during the reconstruction, these might look strange as they show a view from the top left of the volume.
Could you provide an example image?

**Comment by thunil** [comment]
Seems to be solved :)
